version: "3"

services:
    projecttpb:
        build:
            context: .
            dockerfile: Dockerfile
        image: projecttpb-app
        container_name: projecttpb-app
        restart: unless-stopped
        ports:
            - "8001:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./storage:/var/www/storage
            - ./.env:/var/www/.env
        networks:
            - projecttpb-network

networks:
    projecttpb-network:
        driver: bridge
