services:
    portaltpb-app:
        container_name: portaltpb-app
        image: portaltpb
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8001:80'
        environment:
            DB_HOST: host.docker.internal
        volumes:
            - ./storage:/var/www/html/storage
            - ./.env:/var/www/html/.env
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - portaltpb-network

networks:
    portaltpb-network:
        driver: bridge
